version: '3.8'

services:
  # Serviço do banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: agenda_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Flfsd12kFl!dfs11
      MYSQL_DATABASE: agenda_db
      MYSQL_USER: agenda_user
      MYSQL_PASSWORD: Dlf_d88Ff0asCC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agenda_network

  # Serviço do PHP para o backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agenda_backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - agenda_network

  # Serviço do React para o frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agenda_frontend
    restart: always
    volumes:
      - ./frontend:/app:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - agenda_network

  # Serviço do phpMyAdmin para gestão do banco de dados (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: agenda_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Flfsd12kFl!dfs11
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - agenda_network

networks:
  agenda_network:
    driver: bridge

volumes:
  mysql_data:
  frontend_node_modules: